export const currencyListItems = [
    {
      id: 137,
      name: 'Pakistan',
      flag:'PK',
      currname: 'Pakistani Rupee',
      currency: 'PKR',
    },
    {
      id: 1,
      name: 'United States',
      flag:'US',
      currname: 'US Dollar',
      currency: 'USD',
    },
    {
      id: 3,
      name: 'United Kingdom',
      flag: 'GB',
      currname: 'Pound Sterling',
      currency: 'GBP',
    },
    {
      id: 5,
      name: 'Canada',
      flag: 'CA',
      currname: 'Canadian Dollar',
      currency: 'CAD',
    },
    {
      id: 6,
      name: 'Argentina',
      flag: 'AR',
      currname: 'Argentine Peso',
      currency: 'ARS',
    },
    {
      id: 7,
      name: 'Australia',
      flag: 'AU',
      currname: 'Australian Dollar',
      currency: 'AUD',
    },
    {
      id: 8,
      name: 'Brazil',
      flag: 'BR',
      currname: 'Brazilian Real',
      currency: 'BRL',
    },
    {
      id: 9,
      name: 'Chile',
      flag: 'CL',
      currname: 'Chilean Peso',
      currency: 'CLP',
    },
    {
      id: 10,
      name: 'China',
      flag: 'CN',
      currname: 'Yuan Renminbi',
      currency: 'CNY',
    },
    {
      id: 2,
      name: 'European Union',
      flag: 'US',
      currname: 'Euro',
      currency: 'EUR',
    },
    {
      id: 11,
      name: 'Cyprus',
      flag: 'CY',
      currname: '',
      currency: 'CYP',
    },
    {
      id: 12,
      name: 'Czech Republic',
      flag: 'CZ',
      currname: 'Czech Koruna',
      currency: 'CZK',
    },
    {
      id: 13,
      name: 'Denmark',
      flag: 'DK',
      currname: 'Danish Krone',
      currency: 'DKK',
    },
    {
      id: 15,
      name: 'Hong Kong',
      flag: 'HK',
      currname: 'Hong Kong Dollar',
      currency: 'HKD',
    },
    {
      id: 16,
      name: 'Hungary',
      flag: 'HU',
      currname: 'Forint',
      currency: 'HUF',
    },
    {
      id: 17,
      name: 'Iceland',
      flag: 'IS',
      currname: 'Iceland Krona',
      currency: 'ISK',
    },
    {
      id: 18,
      name: 'India',
      flag: 'IN',
      currname: 'Indian Rupee',
      currency: 'INR',
    },
    {
      id: 19,
      name: 'Jamaica',
      flag: 'JM',
      currname: 'Jamaican Dollar',
      currency: 'JMD',
    },
    {
      id: 20,
      name: 'Japan',
      flag: 'JP',
      currname: 'Yen',
      currency: 'JPY',
    },
    {
      id: 21,
      name: 'Unkown',
      flag: 'LV',
      currname: '',
      currency: 'LVL',
    },
    {
      id: 22,
      name: 'Unkown',
      flag: 'LT',
      currname: '',
      currency: 'LTL',
    },
    {
      id: 23,
      name: 'Unkown',
      flag: 'MT',
      currname: '',
      currency: 'MTL',
    },
    {
      id: 24,
      name: 'Mexico',
      flag: 'MX',
      currname: 'Mexican Peso',
      currency: 'MXN',
    },
    {
      id: 25,
      name: 'New Zealand',
      flag: 'NZ',
      currname: 'New Zealand Dollar',
      currency: 'NZD',
    },
    {
      id: 26,
      name: 'Norway',
      flag: 'NO',
      currname: 'Norwegian Krone',
      currency: 'NOK',
    },
    {
      id: 27,
      name: 'Poland',
      flag: 'PL',
      currname: 'Zloty',
      currency: 'PLN',
    },
    {
      id: 28,
      name: 'Singapore',
      flag: 'SG',
      currname: 'Singapore Dollar',
      currency: 'SGD',
    },
    {
      id: 31,
      name: 'South Africa',
      flag: 'ZA',
      currname: 'Rand',
      currency: 'ZAR',
    },
    {
      id: 32,
      name: 'Korea',
      flag: 'KR',
      currname: 'Won',
      currency: 'KRW',
    },
    {
      id: 33,
      name: 'Sweden',
      flag: 'SE',
      currname: 'Swedish Krona',
      currency: 'SEK',
    },
    {
      id: 34,
      name: 'Switzerland',
      flag: 'CH',
      currname: 'Swiss Franc',
      currency: 'CHF',
    },
    {
      id: 35,
      name: 'Taiwan',
      flag: 'TW',
      currname: 'New Taiwan Dollar',
      currency: 'TWD',
    },
    {
      id: 36,
      name: 'Uruguay',
      flag: 'UY',
      currname: 'Peso Uruguayo',
      currency: 'UYU',
    },
    {
      id: 37,
      name: 'Malaysia',
      flag: 'MY',
      currname: 'Malaysian Ringgit',
      currency: 'MYR',
    },
    {
      id: 38,
      name: 'Bahamas',
      flag: 'BS',
      currname: 'Bahamian Dollar',
      currency: 'BSD',
    },
    {
      id: 39,
      name: 'Costa Rica',
      flag: 'CR',
      currname: 'Costa Rican Colon',
      currency: 'CRC',
    },
    {
      id: 41,
      name: 'Philippines',
      flag: 'PH',
      currname: 'Philippine Peso',
      currency: 'PHP',
    },
    {
      id: 42,
      name: 'United Arab Emirates',
      flag: 'AE',
      currname: 'UAE Dirham',
      currency: 'AED',
    },
    {
      id: 44,
      name: 'Indonesia',
      flag: 'ID',
      currname: 'Rupiah',
      currency: 'IDR',
    },
    {
      id: 45,
      name: 'Turkey',
      flag: 'TR',
      currname: 'Turkish Lira',
      currency: 'TRY',
    },
    {
      id: 46,
      name: 'Thailand',
      flag: 'TH',
      currname: 'Baht',
      currency: 'THB',
    },
    {
      id: 47,
      name: 'Trinidad and Tobago',
      flag: 'TT',
      currname: 'Trinidad and Tobago Dollar',
      currency: 'TTD',
    },
    {
      id: 48,
      name: 'Israel',
      flag: 'IL',
      currname: 'New Israeli Sheqel',
      currency: 'ILS',
    },
    {
      id: 49,
      name: 'Syrian Arab Republic',
      flag: 'SY',
      currname: 'Syrian Pound',
      currency: 'SYP',
    },
    {
      id: 50,
      name: 'Antigua and Barbuda',
      flag: 'US',
      currname: 'East Caribbean Dollar',
      currency: 'XCD',
    },
    {
      id: 51,
      name: 'Colombia',
      flag: 'CO',
      currname: 'Colombian Peso',
      currency: 'COP',
    },
    {
      id: 52,
      name: 'Russian Federation',
      flag: 'RU',
      currname: 'Russian Ruble',
      currency: 'RUB',
    },
    {
      id: 53,
      name: 'Croatia',
      flag: 'HR',
      currname: 'Kuna',
      currency: 'HRK',
    },
    {
      id: 54,
      name: 'Kazakhstan',
      flag: 'KZ',
      currname: 'Tenge',
      currency: 'KZT',
    },
    {
      id: 55,
      name: 'Tanzania',
      flag: 'TZ',
      currname: 'Tanzanian Shilling',
      currency: 'TZS',
    },
    {
      id: 57,
      name: 'Saudi Arabia',
      flag: 'SA',
      currname: 'Saudi Riyal',
      currency: 'SAR',
    },
    {
      id: 58,
      name: 'Nicaragua',
      flag: 'NI',
      currname: 'Cordoba Oro',
      currency: 'NIO',
    },
    {
      id: 59,
      name: 'Lao People Democratic Republic ',
      flag: 'LA',
      currname: 'Kip',
      currency: 'LAK',
    },
    {
      id: 60,
      name: 'Oman',
      flag: 'OM',
      currname: '	Rial Omani',
      currency: 'OMR',
    },
    {
      id: 601,
      name: 'Armenia',
      flag: 'AM',
      currname: 'Armenian Dram',
      currency: 'AMD',
    },
    {
      id: 61,
      name: 'Kenya',
      flag: 'KE',
      currname: 'Kenyan Shilling',
      currency: 'KES',
    },
    {
      id: 62,
      name: 'Libya',
      flag: 'LY',
      currname: 'Libyan Dinar',
      currency: 'LYD',
    },
    {
      id: 63,
      name: 'Algeria',
      flag: 'DZ',
      currname: 'Algerian Dinar',
      currency: 'DZD',
    },
    {
      id: 64,
      name: 'Nigeria',
      flag: 'NG',
      currname: 'Naira',
      currency: 'NGN',
    },
    {
      id: 65,
      name: 'Uganda',
      flag: 'UG',
      currname: 'Uganda Shilling',
      currency: 'UGX',
    },
    {
      id: 66,
      name: 'Mongolia',
      flag: 'MN',
      currname: 'Tugrik',
      currency: 'MNT',
    },
    {
      id: 67,
      name: 'Serbia',
      flag: 'RS',
      currname: 'Serbian Dinar',
      currency: 'RSD',
    },
    {
      id: 68,
      name: 'Egypt',
      flag: 'EG',
      currname: 'Egyptian Pound',
      currency: 'EGP',
    },
    {
      id: 69,
      name: 'Nepal',
      flag: 'NP',
      currname: 'Nepalese Rupee',
      currency: 'NPR',
    },
    {
      id: 70,
      name: 'Iran',
      flag: 'IR',
      currname: 'Iranian Rial',
      currency: 'IRR',
    },
    {
      id: 71,
      name: 'Lebanon',
      flag: 'LB',
      currname: 'Lebanese Pound',
      currency: 'LBP',
    },
    {
      id: 72,
      name: 'Swaziland',
      flag: 'SZ',
      currname: 'Lilangeni',
      currency: 'SZL',
    },
    {
      id: 73,
      name: 'Jordan',
      flag: 'JO',
      currname: 'Jordanian Dinar',
      currency: 'JOD',
    },
    {
      id: 74,
      name: 'Yemen',
      flag: 'YE',
      currname: 'Yemeni Rial',
      currency: 'YER',
    },
    {
      id: 75,
      name: 'Tajikistan',
      flag: 'TJ',
      currname: 'Somoni',
      currency: 'TJS',
    },
    {
      id: 76,
      name: 'Sri Lanka',
      flag: 'LK',
      currname: 'Sri Lanka Rupee',
      currency: 'LKR',
    },
    {
      id: 77,
      name: 'Sudan',
      flag: 'SD',
      currname: 'Sudanese Pound',
      currency: 'SDG',
    },
    {
      id: 78,
      name: 'Viet nam',
      flag: 'VN',
      currname: 'Dong',
      currency: 'VND',
    },
    {
      id: 79,
      name: 'Ukraine',
      flag: 'UA',
      currname: 'Hryvnia',
      currency: 'UAH',
    },
    {
      id: 80,
      name: 'Turkmenistan',
      flag: 'TM',
      currname: 'Turkmenistan New Manat',
      currency: 'TMT',
    },
    {
      id: 81,
      name: 'Iraq',
      flag: 'IQ',
      currname: 'Iraqi Dinar',
      currency: 'IQD',
    },
    {
      id: 82,
      name: 'Kyrgyzstan',
      flag: 'KG',
      currname: 'Som',
      currency: 'KGS',
    },
    {
      id: 83,
      name: 'Uzbekistan',
      flag: 'UZ',
      currname: 'Uzbekistan Sum',
      currency: 'UZS',
    },
    {
      id: 84,
      name: 'Afghanistan',
      flag: 'AF',
      currname: 'Afghani',
      currency: 'AFN',
    },
    {
      id: 85,
      name: 'Bangladesh',
      flag: 'BD',
      currname: 'Taka',
      currency: 'BDT',
    },
    {
      id: 86,
      name: 'Azerbaijan',
      flag: 'AZ',
      currname: 'Azerbaijanian Manat',
      currency: 'AZN',
    },
    {
      id: 87,
      name: 'Qatar',
      flag: 'QA',
      currname: 'Qatari Rial',
      currency: 'QAR',
    },
    {
      id: 88,
      name: 'Kuwait',
      flag: 'KW',
      currname: 'Kuwaiti Dinar',
      currency: 'KWD',
    }

];

export default {
    currencyListItems,
}
  




























